repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
    -   id: auto-walrus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.13.1"
    hooks:
      - id: pyproject-fmt

  - repo: local
    hooks:
      - id: validate-filenames
        name: Validate filenames
        entry: ./scripts/validate_filenames.py
        language: script
        pass_filenames: false

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.14
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --install-types # See mirrors-mypy README.md
          - --non-interactive
        additional_dependencies: [types-requests]
