[tool.pytest.ini_options]
markers = [
    "mat_ops: mark a test as utilizing matrix operations.",
]
addopts = [
    "--durations=10",
    "--doctest-modules",
    "--showlocals",
]


[tool.coverage.report]
omit = [".env/*"]
sort = "Cover"

#[report]
#sort = Cover
#omit =
#    .env/*
#    backtracking/*
